<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>welcome</name>
   <tag></tag>
   <elementGuidId>1a67b9d8-0a6b-4348-9b19-efd37e60b4bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id='nameofuser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='nameofuser']</value>
      <webElementGuid>dd9a0b2b-f752-4c87-a11f-8148afe6bcf4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
