<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>year</name>
   <tag></tag>
   <elementGuidId>fd9dd0b0-5bd8-4480-ae24-3b2787d0b37b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='year']</value>
      <webElementGuid>47d9cdc7-f1f8-4f63-b951-65f4e889dbf5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
