<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_apple</name>
   <tag></tag>
   <elementGuidId>b58a6ba2-51b6-4b5e-8216-bbf2cce73c09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h2[@class='name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[@class='name']</value>
      <webElementGuid>2eb14f8b-4b29-4efb-ab63-b19d94178c41</webElementGuid>
   </webElementProperties>
</WebElementEntity>
