<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>phone</name>
   <tag></tag>
   <elementGuidId>794d98a5-dfe0-4b95-9575-eb383287b0be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[.='Phones']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[.='Phones']</value>
      <webElementGuid>a1918eed-27f3-4403-b69a-a2d24cbb0bfe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
